[package]
name = "purple-garden"
version = "0.1.0"
description = "Lean scripting language, designed and implemented with a focus on performance and a low memory profile "
edition = "2024"

[features]
trace = []
nightly = []

[dependencies]

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
